apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
  name: add-tags
  namespace: default
spec:
  description: This Task add additional tags to a docker image
  params:
  - description: The output registry
    name: registry
    type: string
  - description: The image to retag
    name: source_image
    type: string
  - description: The source digest
    name: source_digest
    type: string
  - description: additional tags
    name: tags
    type: array
  - default: "true"
    description: Validate TLS connection
    name: tls_verify
    type: string
  - default: ""
    description: additional arguments
    name: extra_args
    type: string
  - default: .
    description: Path to the directory to use as context.
    name: context
    type: string
  steps:
  - args:
    - $(params.tags)
    computeResources: {}
    image: registry.redhat.io/ubi9/skopeo@sha256:0c1b2a4e99d715a3023d0a2e934b6d5d4154afc556ccd24314251b9add0654ad
    name: re-tag
    script: |-
      #!/bin/bash
      set -xe

      CRED_FILE="$(workspaces.creds.path)/.dockerconfigjson"
      if [[ -f "${CRED_FILE}" ]]; then
          echo "Using provided credentials"
          CRED="--dest-authfile ${CRED_FILE} --src-authfile ${CRED_FILE}"
      fi

      TAGS=($@)

      for tag in "${TAGS[@]}"; do
        skopeo copy \
          $CRED \
          --src-tls-verify=$(params.tls_verify) \
          --dest-tls-verify=$(params.tls_verify) \
          $(params.extra_args) \
          docker://$(params.registry)/$(params.source_image)@$(params.source_digest) \
          docker://$(params.registry)/$(params.source_image):$tag
      done

      semver_tag=$(cat /workspace/output/$(params.context)/VERSION)
      
      skopeo copy $CRED \
          --src-tls-verify=$(params.tls_verify) \
          --dest-tls-verify=$(params.tls_verify) \
          $(params.extra_args) \
          docker://$(params.registry)/$(params.source_image)@$(params.source_digest) \
          docker://$(params.registry)/$(params.source_image):$semver_tag
  workspaces:
  - description: Docker registry credentials
    name: creds
  - description: Docker output directory
    name: output
