apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build
  name: changed-dirs
  namespace: ai-workbench-pipelines 
spec:
  description: |-
    task to get the context dirs for builds
  params:
  - description: where to actually look
    name: folder_pattern
    type: string
    default: images
  - default: registry.redhat.io/rhel8/buildah@sha256:3c2ea396a114221575a4031d90d28c43563f7b96288374e0ba8b22de3ed97b5a
    description: The image providing the git-init binary that this Task runs.
    name: gitInitImage
    type: string
  results:
  - description: comma seperated list of changed directories
    name: changed_dirs
    type: string
  steps:
  - computeResources: {}
    image: $(params.gitInitImage)
    name: build-and-push
    script: |
        #!/usr/bin/env bash

        set -eux

        echo $(workspaces.source.path)
        cd $(workspaces.source.path)

        ls -laR
        pwd

        git config --global --add safe.directory "$(workspaces.source.path)"

        /bin/sh

        # Finding changed directories that match the provided pattern between
        #the current and previous commit

        git diff HEAD~1 HEAD --name-only
        CHANGED_DIRS=$(git diff HEAD~1 HEAD --name-only | grep \
        '$(params.folder_pattern)' | xargs -r -n 1 dirname | sort -u | tr '\n' ',')

        # Remove the trailing comma

        CHANGED_DIRS=${CHANGED_DIRS%,}

        echo -n "$CHANGED_DIRS" > $(results.changed_dirs.path)
        echo $CHANGED_DIRS


  workspaces:
  - name: source
    description: Workspace to change file dirs.  
