apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
  name: build-push
  namespace: default
spec:
  params:
  - description: The git repo to pull from
    name: gitrepo
    type: string
  - description: The image and tag to build
    name: imgname
    type: string
  - description: The git revision
    name: gitrev
    type: string
  - description: The registry name
    name: registry
    type: string
  - description: The image tag
    name: imgtag
    type: string
  - default: wordpress/website
    name: kustomize-dir
    type: string
  - name: manifest-repo
    type: string
  - description: Where file
    name: context
    type: string
  tasks:
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.registry)/$(params.imgname):$(tasks.git-clone.results.commit)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:3c2ea396a114221575a4031d90d28c43563f7b96288374e0ba8b22de3ed97b5a
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Containerfile
    - name: CONTEXT
      value: $(params.context)
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: buildah
    workspaces:
    - name: source
      workspace: output
    - name: dockerconfig
      workspace: dockercred
    - name: src-docker
      workspace: src-docker
  - name: add-tags
    params:
    - name: registry
      value: $(params.registry)
    - name: source_image
      value: $(params.imgname)
    - name: source_digest
      value: $(tasks.buildah.results.IMAGE_DIGEST)
    - name: tags
      value:
      - $(params.imgtag)
      - latest
    - name: tls_verify
      value: "true"
    - name: extra_args
      value: ""
    runAfter:
    - buildah
    taskRef:
      kind: Task
      name: add-tags
    workspaces:
    - name: creds
      workspace: dockercred
  - name: git-clone
    params:
    - name: url
      value: $(params.gitrepo)
    - name: revision
      value: $(params.gitrev)
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
    - name: userHome
      value: /home/git
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: output
  workspaces:
  - name: output
  - name: dockercred
  - name: src-docker
