apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ai-workbench-pipelines-event-listener
  namespace: ai-workbench-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptors:
        - name: Validate github payload and filter on eventype
          params:
            - name: filter
              value: 'body.ref in [''refs/heads/main'', ''refs/heads/master'']'
          ref:
            kind: ClusterInterceptor
            name: cel
      bindings:
        - ref: ai-workbench-trigger-binding
      template:
        ref: ai-workbench-pipelines-trigger-template
        