apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ai-workbench-trigger-binding
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-commit-message
      value: $(body.head_commit.message)
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: content-type
      value: $(header.Content-Type)
    - name: pusher-name
      value: $(body.pusher.name)
    - name: modified-files
      value: $(body.head_commit.modified)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
 name: ai-workbench-pipelines-trigger-template
spec:
 params:
 - name: git-repo-url
#  - name: gitrepositoryurl
#  - name: pull_request_title
 resourcetemplates:
 - apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     generateName: ai-workbench-pipelines-trigger-
   spec:
     pipelineRef:
       name: build-push
     params:
        - name: gitrepo
          value: $(tt.params.git-repo-url)
        - name: imgname
          value: simple-jupyter
        - name: gitrev
          value: main
        - name: registry
          value: quay.io/rh_ee_akugel
        - name: imgtag
          value: latest
        - name: context
          value: images/simple-jupyter

     workspaces:
        - name: output
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: gp3-csi # this will need to change if not on aws
              volumeMode: Filesystem
            status: {}
        - name: dockercred
          secret:
            secretName: rh-ee-akugel-tektonic-pull-secret
        - name: src-docker
          secret:
            secretName: redhatregistryio