apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
 name: ai-workbench-pipelines-trigger-template
spec:
 params:
 - name: gitrevision
 - name: gitrepositoryurl
 - name: pull_request_title
 resourcetemplates:
 - apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     generateName: ai-workbench-pipelines-trigger-
   spec:
     pipelineRef:
       name: build-push
     resources:
       - name: app-source
         resourceSpec:
           type: git
           params:
           - name: revision
             value: $(params.gitrevision)
           - name: url
             value: $(params.gitrepositoryurl)
     Params:
       - name: title
         value: $(params.pull_request_title)
       - name: revision
         value: $(params.gitrevision)
       - name: url
         value: $(params.gitrepositoryurl)