FROM registry.access.redhat.com/ubi9/python-311@sha256:fae422b4e7dbc2e551919fb87b6004c06b731179be2ed2904427531a2d1ef3a2
### The image tag is 1-62.1714671026, published on 2024-05-06

COPY --chown=1001:0 requirements.txt .
COPY --chown=1001:0 start-notebook.sh /opt/app-root/bin

RUN pip install -r requirements.txt && \
    fix-permissions /opt/app-root -P

EXPOSE 8888

ENTRYPOINT ["start-notebook.sh"]
